Do not assume any code-tables on strings in python2
Scripts should never assume what codetable an external user has
and try to decode. Doing that has huge potential to cause pain and
misery for users (a common python3 sickness nowadays).

:This is a hard problem to solve for pytho3 but we shouldn't inflict
that damage and overhead on python2 users.

Here's one example of this failure on Jessie with backports 4.9 kernel:

Traceback (most recent call last):
  File "../../tools/slabratetop.py", line 123, in <module>
    print("%-32s %6d %10d" % (k.name.decode(), v.count, v.size))
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc1 in position 2: ordinal not in range(128)